### PR TITLE
week2

### PR DESCRIPTION
**Pull request by bishoy-magdy**
# What has been done

- Added a login screen (view Panel).
- Added close behavior to the panel.

# Screenshot
login

### CODE REVIEW

**Comment by roman-r-m** [comment]
Looking at the screenshot it's not exactly clear to me what it means to manually connect to IMAP

**Comment by bishoy-magdy** [comment]
> Looking at the screenshot it's not exactly clear to me what it means to manually connect to IMAP

It is for custom emails, such as company emails that have a unique domain and therefore have a custom imap like : 
`employee@company.com 
`So the imap host is `imap.company.com` or `imap.mail.company.com` not standard

Or if you have a custom email address on a web hosting service like hostinger, so the imap host is `imap.hostinger.com`.

So when the user clicks on the manual connection, I will take the email, password, imap host, port number, and encryption (SSL or TLS), and these are the configurations for making an imap connection.

Whether you own an email from famous email providers like Gmail, Yahoo, Outlook,... or a custom email, you can connect to a plugin.

**Comment by roman-r-m** [comment]
Looks good to me!

**Comment by bishoy-magdy** [comment]
> Looks good to me!

If all is good, can this be merged :)?

**Comment by roman-r-m** [comment]
Sure. Sorry, should have done it back then

**Pull request merged**
